version: '3.9'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexa
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: 8080
      DATABASE_URL: postgresql://postgres:postgres@db:5432/nexa?schema=public
      JWT_SECRET: devsecret
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: ["pnpm","dev:docker"]

  frontend:
    build: ./frontend
    environment:
      VITE_GRAPHQL_URL: http://localhost:8080/graphql
      VITE_REST_URL: http://localhost:8080
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:
