services:
  - type: web
    name: nexa-backend
    env: docker
    rootDir: backend
    healthCheckPath: /health
    # ...

staticSites:
  - name: nexa-frontend
    rootDir: frontend
    buildCommand: pnpm i && pnpm build
    publishPath: dist
    # variables VITE_* para el build del front:
    envVars:
      - key: VITE_GRAPHQL_URL
        # value: https://TU-BACKEND.onrender.com/graphql
        sync: false
      - key: VITE_REST_URL
        # value: https://TU-BACKEND.onrender.com
        sync: false

databases:
  - name: nexa-postgres
