services:
  - type: web
    name: nexa-backend
    env: docker
    rootDir: backend
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        # pon un secreto cualquiera para demo, ej: nexa_demo_secret_123
        value: nexa_demo_secret_123
      - key: DATABASE_URL
        # la pondrás en el panel de Render al final (o cámbiala aquí cuando tengas Neon)
        sync: false
      - key: CORS_ORIGIN
        # pon * para PMV si quieres ir rápido; luego cámbialo a la URL real del front
        value: "*"
      - key: VITE_GRAPHQL_URL
        # opcional/informativo, el front usa sus propias VITE_* en build
        sync: false

  - type: web
    name: nexa-frontend
    env: static
    rootDir: frontend
    buildCommand: pnpm i && pnpm build
    staticPublishPath: dist
    envVars:
      - key: VITE_GRAPHQL_URL
        # La pondrás en el panel cuando tengas la URL del backend
        sync: false
      - key: VITE_REST_URL
        # La pondrás en el panel cuando tengas la URL del backend
        sync: false
